# Stage 01: Data Collection

Fetch historical F1 data (2014–2024) from the Ergast Developer API and save as raw CSV files.

**Data sources:**
- Race results (finishing positions, points, status)
- Qualifying results (Q1, Q2, Q3 times)
- Circuit information (name, country, coordinates)

In [1]:
import sys
sys.path.append('..')

from src.data_pipeline import (
    fetch_race_results,
    fetch_qualifying_results,
    fetch_circuits,
    save_raw_data,
    get_data_summary
)

## 1.1 Fetch Race Results

In [2]:
race_df = fetch_race_results(start_year=2014, end_year=2024)
print(f"Race results: {race_df.shape}")
race_df.head()

Fetched 2014 race results

Fetched 2015 race results

Fetched 2016 race results

Fetched 2017 race results

Fetched 2018 race results

Fetched 2019 race results

Fetched 2020 race results

Fetched 2021 race results

Fetched 2022 race results

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

Fetched 2023 race results

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

Fetched 2024 race results
Race results: (4626, 15)

,season,round,raceName,circuitId,driverCode,givenName,familyName,driverId,constructorName,constructorId,grid,position,points,status,laps
0,2014,1,Australian Grand Prix,albert_park,ROS,Nico,Rosberg,rosberg,Mercedes,mercedes,3,1,25.0,Finished,57
1,2014,1,Australian Grand Prix,albert_park,MAG,Kevin,Magnussen,kevin_magnussen,McLaren,mclaren,4,2,18.0,Finished,57
2,2014,1,Australian Grand Prix,albert_park,BUT,Jenson,Button,button,McLaren,mclaren,10,3,15.0,Finished,57
3,2014,1,Australian Grand Prix,albert_park,ALO,Fernando,Alonso,alonso,Ferrari,ferrari,5,4,12.0,Finished,57
4,2014,1,Australian Grand Prix,albert_park,BOT,Valtteri,Bottas,bottas,Williams,williams,15,5,10.0,Finished,57

## 1.2 Fetch Qualifying Results

In [3]:
qualifying_df = fetch_qualifying_results(start_year=2014, end_year=2024)
print(f"Qualifying results: {qualifying_df.shape}")
qualifying_df.head()

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

Fetched 2014 qualifying results

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

Fetched 2015 qualifying results

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

Fetched 2016 qualifying results

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

Fetched 2017 qualifying results

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

Fetched 2018 qualifying results

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

Fetched 2019 qualifying results

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

Fetched 2020 qualifying results

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

Fetched 2021 qualifying results

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

Fetched 2022 qualifying results

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

Fetched 2023 qualifying results

  Rate limited, waiting 2s...

  Rate limited, waiting 2s...

Fetched 2024 qualifying results
Qualifying results: (4610, 10)

,season,round,circuitId,driverCode,driverId,constructorName,qualifyingPosition,Q1,Q2,Q3
0,2014,1,albert_park,HAM,hamilton,Mercedes,1,1:31.699,1:42.890,1:44.231
1,2014,1,albert_park,RIC,ricciardo,Red Bull,2,1:30.775,1:42.295,1:44.548
2,2014,1,albert_park,ROS,rosberg,Mercedes,3,1:32.564,1:42.264,1:44.595
3,2014,1,albert_park,MAG,kevin_magnussen,McLaren,4,1:30.949,1:43.247,1:45.745
4,2014,1,albert_park,ALO,alonso,Ferrari,5,1:31.388,1:42.805,1:45.819

## 1.3 Fetch Circuit Information

In [4]:
circuits_df = fetch_circuits()
print(f"Circuits: {circuits_df.shape}")
circuits_df.head()

Circuits: (78, 5)

     circuitId                     circuitName    country      lat        lng
0     adelaide         Adelaide Street Circuit  Australia -34.9272  138.61700
1     ain-diab                        Ain Diab    Morocco  33.5786   -7.68750
2      aintree                         Aintree         UK  53.4769   -2.94056
3  albert_park  Albert Park Grand Prix Circuit  Australia -37.8497  144.96800
4     americas         Circuit of the Americas        USA  30.1328  -97.64110

## 1.4 Save Raw Data

In [5]:
save_raw_data(race_df, qualifying_df, circuits_df)

Saved raw data to C:\Users\brian\OneDrive\Desktop\Project\notebooks\..\src\..\data\raw

## 1.5 Validate Data

In [6]:
get_data_summary()

Race Results: 4626 rows, 15 columns
  Columns: ['season', 'round', 'raceName', 'circuitId', 'driverCode', 'givenName', 'familyName', 'driverId', 'constructorName', 'constructorId', 'grid', 'position', 'points', 'status', 'laps']

Qualifying: 4610 rows, 10 columns
  Columns: ['season', 'round', 'circuitId', 'driverCode', 'driverId', 'constructorName', 'qualifyingPosition', 'Q1', 'Q2', 'Q3']

Circuits: 78 rows, 5 columns
  Columns: ['circuitId', 'circuitName', 'country', 'lat', 'lng']

In [7]:
# Quick validation checks
print(f"\nSeasons covered: {race_df['season'].min()} - {race_df['season'].max()}")
print(f"Unique drivers: {race_df['driverId'].nunique()}")
print(f"Unique circuits: {race_df['circuitId'].nunique()}")
print(f"Missing positions: {race_df['position'].isna().sum()}")
print(f"\nRaces per season:")
print(race_df.groupby('season')['round'].max())

Seasons covered: 2014 - 2024
Unique drivers: 59
Unique circuits: 32
Missing positions: 0

Races per season:
season
2014    19
2015    19
2016    21
2017    20
2018    21
2019    21
2020    17
2021    22
2022    22
2023    22
2024    24
Name: round, dtype: int64